spring:
  application:
    name: kanban
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: kanban
    password: kanban
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security.oauth2.client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        scope: openid, email, profile
      keycloak:
        client-id: kanban-app
        client-secret: JQUoD1jz2U18cnyllrmO7RSBP5igfDhh
        redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
        scope: openid, email, profile
    provider:
      keycloak:
        issuer-uri: http://localhost:9080/realms/kanban
  session:
    store-type: redis
  data:
    redis:
      host: ${VALKEY_HOST:localhost}
      port: ${VALKEY_PORT:6379}

gg.jte:
  development-mode: false
  use-precompiled-templates: true
  template-suffix: .kte